### PR TITLE
Issues #16 / #32 / #34 / #36 / #37 / #40 / #63 / #64

### PR DESCRIPTION
**Pull request by judgej**
Issues #16 / #32 / #34 / #36 / #37 / #40 / #63 / #64

Still not complete (needs more tests and docblocks, but functionally complete) and getting up for visibility and automated testing.

This is a rewrite of the notification handler using the newer `NotificationInterface`. All the listed issues revolve around the notification handling, which has always been a bit "special".

This PR provides a new way to handle the notifications, but does not introduce any BC breaks for existing applications. However, updating the applications should simplify their notification handlers somewhat.

### CODE REVIEW

**Comment by judgej** [comment]
Summary of changes in relation so specific issues are:

* #16 An invalid signature will no longer raise an exception unless you try to respond to Sage Pay with a `error` or `confirm`; you must response with an `invalid`. A `checkSignature()` method gives you a true/false indication of whether the signature is valid.
* #32
* #34
* #36
* #37
* #40
* #63
* #64

**Comment by judgej** [comment]
Check out the documentation in the updated README.md for how this is used.

**Comment by delatbabel** [comment]
Looks good to me.  I'm not aware of any other gateways that use AcceptNotification or accept or whatever but I'm considering implementing it in two that do send notifications. Let me know how this goes and I'll likely use it as a model.

**Comment by judgej** [comment]
I wonder if `accept` and `decline` would be better than `confirm` and `error` when responding to the notification, keeping `invalid` in there for failed signatures? They are closer to the language that the gateways use (which may not be a good thing if it causes confusion).

**Comment by judgej** [comment]
I'm also implementing the `notify` message in the new PAYONE driver, so am trying to get these both consistent where possible:

https://github.com/academe/OmniPay-Payone

**Comment by lukeholder** [comment]
Hi @judgej, I am the developer of Craft Commerce. I was made aware you are doing some work here to assist us get support for Sagepay Server. Happy to have a skype call, or take your advice as to how we can make our software compatible with the above changes.

skype: lukemholder

**Comment by lukeholder** [comment]
thumbs up with`::acceptNotification()` instead of `::notify()`. (As it is named in the README)

One example of `acceptNotification` I found in active use:
https://github.com/collizo4sky/omnipay-2checkout/blob/master/src/Gateway.php#L230

**Comment by judgej** [comment]
Thanks, I'll change that.

**Comment by judgej** [comment]
@lukeholder It would probably be just as easy to implement the old notification handler for now then change it later when this is fixed. 80% of the code will remain the same, with the update mostly involving removing some stuff. Old and new ultimately do the same thing. The old method is just less intuitive to implement, but I can guide you through that.

I still have tests to write for this before it can go live, and there are a few other PRs I desperately need to look at. Could give you a call this afternoon.

**Comment by judgej** [comment]
Okay, I messed up. That serves me right for trying to juggle half a dozen branches at the same time. So - this can remain or it can be removed and reverted back to a PR - except I am not entirely clear on how to do that.

**Comment by judgej** [comment]
I really don't know what has happened here, because I can't actually see many of these changes that have apparently been merged in. I'll just create another PR - is says in my source repo that it has not been merged, even though it says here that it has :confused:

**Comment by judgej** [comment]
Okay - I think it is all sorted now - a new PR #69 to replace this one, and master reverted back to before my mess-up.

**Pull request merged**
