### PR TITLE
PR #107 fixes character stripping allowed chars  and adds tests ar…

### PR DESCRIPTION
**Pull request by harnasz**
Fixes stripping for `[]` which breaks the `Sage 50 Accounts Software Integration`. For more details please see  #107 .

The following work has been done:

-   Added individual sanitisation method for non 
XML integration `\Omnipay\SagePay\Message\AbstractRequest::filterNonXmlItemName` 
- Added tests for Non XML Basket Integration
- Extended `\Omnipay\SagePay\Extend\Item` with syntactical sugar for setting the product record for Sage 50 Accounts Software Integration as suggested by @judgej

### CODE REVIEW

**Comment by judgej** [comment]
That looks great :-) The only thing I would change is the parameter key "product_code" to lower camel-case "productCode". It's really minor, but is just a consistency thing with the rest of the package and other gateway drivers.

**Comment by judgej** [comment]
Oh, also try merging in `master`. We can get a few things into the next release, hopefully a fix for issue #104 too, which I think will also open up more features without any BC breaks.

**Comment by harnasz** [comment]
Hey @judgej  - thank you! I've just refactored based upon the feedback you sent yesterday along with merging in master. Let me know if there is anything else I need to do 😄 .

**Comment by judgej** [comment]
Just wondering, you'v used `productRecord` everywhere, while the Sage Pay docs call it `productCode`. Any reason for that?

**Comment by harnasz** [comment]
Hey @judgej, 

From the docs here https://www.sagepay.co.uk/file/12246/download-document/SERVER_Integration_and_Protocol_Guidelines_010814.pdf?token=zlCqBGKB7BlA503YTOOtRsBXWKcI4aVrqNSETHDIspk under `10.0 Sage 50 Accounts Software Integration` they refer to it as `productRecord`. Would you rather it be `productCode`?

**Comment by harnasz** [comment]
@judgej - my bad, it is `productCode`. I'll get this fixed.

**Comment by judgej** [comment]
It talks about using the *product codes* to link the basket lines to the *product records* in Sage 50. It's not very clear, I know.

**Comment by harnasz** [comment]
There we go @judgej  - hugely appreciate your time.

**Comment by judgej** [comment]
Okay, merged in, with an additional to the extended item interface.

**Comment by harnasz** [comment]
Hi @judgej , many thanks.

**Pull request merged**
