### PR TITLE
Attempt to fix travis issue

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Per https://github.com/friends-of-phpspec/phpspec-code-coverage/issues/42#issuecomment-737186962

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@judgej looks like this worked!

**Comment by judgej** [comment]
Woo! No idea why, but we'll run with it. Too many other layers to fill my head with already.

I'm 12 hours behind you, so will be calling it a day soon, but should be back tomorrow to see if there is anything I can do to help.

**Comment by judgej** [comment]
Merged, thanks :-)

**Comment by eileenmcnaughton** [comment]
Nice thanks - & it sounds like it must be night time there well & truly then!

**Pull request merged**
