### PR TITLE
XMLBasket with discounts (extension of PR #50)

### PR DESCRIPTION
**Pull request by judgej**
I've fixed an empty basket issue in PR #50 and added some tests.

### CODE REVIEW

**Comment by judgej** [comment]
Just had a thought - probably needs some tests for negative item prices, to show them appearing as discounts. I'll try and get those in before creating a release.

**Comment by dignat** [comment]
Thank you so much. This is brilliant. I appreciate it.
Thank you once again
Denise

**Comment by coatesap** [comment]
Hi @judgej - any chance of a version bump so we can start using this via composer?

**Comment by judgej** [comment]
Not sure if this should be a patch release (2.2.1) or a point release (2.3.0). It is just new functionality, so should not affect people not using it. However, there could be systems that are passing the basket in anyway, not expecting it to actually work.

I vote for 2.3.0 - it's not as though we are going to run out of version numbers quickly. It just highlights that functionality may change without the merchant site doing anything differently. Agree?

**Comment by coatesap** [comment]
Agreed - 2.3.0 makes most sense as it should count as additional functionality.

**Pull request merged**
