### PR TITLE
Extend item to include VAT property

### LINKED ISSUE #85: Not able to set Tax amount on line items
Relates to this line here: https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/AbstractRequest.php#L303

My suggested fix is to add a custom `SagePayItem` which extends the Omnipay `Item` and exposes a getter/setter for tax amount, then check the Item type in the code linked above.

### PR DESCRIPTION
**Pull request by diego-vieira**
Closes #85 

Note that I set the VAT property to be amount instead of percentage, the reason is because of decimals.

### CODE REVIEW

**Comment by judgej** [comment]
Thanks, lots to look at here.

The `transactionReference` seems to be built from an awful lot of fields now. What was the reasoning for that? The reference was supposed to contain only the fields needed to be able to make another payment or capture the authorisation, and it happens that SagePay needs three or four fields to do that. But there is no need to stuff the rest of the transaction result into the `transactionReference`.

**Comment by diego-vieira** [comment]
@judgej sorry about that, that "Add extra properties" commit was not meant to go towards this PR. Will send another with the correct changes.

**Comment by diego-vieira** [comment]
As with regards to the extra fields in `transactionReference` is just that we need to store on our system the results of AVSCV2, AddressResult, CV2Result, PostCodeResult due to fraud check.

So we will keep our own fork separate to include those changes.

**Comment by judgej** [comment]
The extra fields are all great, so looking forward to that.

**Comment by diego-vieira** [comment]
https://github.com/thephpleague/omnipay-sagepay/pull/96

**Pull request closed without merging**
